name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      run: |
        pwd
        echo -e "\n gradlew assembleRelease \n"
        chmod a+x gradlew
        ./gradlew assembleRelease

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: upload-apk
        path: |
              echo -e "\n show path \n"
              pwd
              ls -l
              ${{github.workspace}}/app/build/outputs/apk/release/*.apk

    - name: Get Time
      id: time
      uses: JantHsueh/get-time-action@master
      with:
        timeZone: 8


