name: Android CI

on:
  push:
    branches:
      - master
      - dev

    tags:
      - 'v*'

  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      id: build
      run: |
        pwd
        echo -e "\n\n gradlew assembleRelease start... \n\n"
        chmod a+x gradlew
        ./gradlew assembleRelease
        echo -e "\n\n"

    - name: Get Time
      id: time
      uses: JantHsueh/get-time-action@master
      with:
        timeZone: 8

    - name: Get Apk Info
      id: apkInfo
      uses: JantHsueh/get-apk-info-action@master
      with:
        apkPath: ./build/app/outputs/apk/release/*.apk

    - name: Get git log
      id: gitLog
      uses: JantHsueh/get-git-log-action@master
      with:
        tag: release

    - name: upload apk
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: QuickDev.apk
        path: ${{ github.workspace }}/build/app/outputs/apk/release/*.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.event.repository.name }} ${{ steps.branch-name.outputs.current_branch }} v${{ steps.apkInfo.outputs.versionNum }} ${{ steps.apk.outputs.versionCode }} ${{ steps.time.outputs.time}}

    - name: Upload File to Pgyer
      id: upload
      uses: JantHsueh/upload-file-action@master
      with:
        url: https://www.pgyer.com/apiv2/app/upload
        forms: '{"_api_key":"${{ secrets.pgyer_key }}","buildInstallType":3}'
        fileForms: '{"file":"releases/Android_Dev_Quick_release.apk"}'
